create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password_hash varchar(255) not null
);

create table if not exists auth_tokens (
    id bigint generated by default as identity primary key,
    token_hash varchar(64) not null unique,
    user_id bigint not null references app_users(id),
    expires_at timestamp with time zone not null
);

create table if not exists cycles (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id),
    start_date date not null,
    end_date date
);

create table if not exists medications (
    id bigint generated by default as identity primary key,
    cycle_id bigint not null unique references cycles(id),
    start_day integer not null,
    end_day integer not null,
    taken boolean not null
);
